services:
  app:
    build:
      context: ./app
    container_name: observa-app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - observanet

  prometheus:
    image: prom/prometheus:latest
    container_name: observa-prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-lifecycle"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro
    ports:
      - "9090:9090"
    networks:
      - observanet
    depends_on:
      - app
      - alertmanager

  alertmanager:
    image: prom/alertmanager:latest
    container_name: observa-alertmanager
    volumes:
      - ./alertmanager/config.yml:/etc/alertmanager/config.yml:ro
    command:
      - "--config.file=/etc/alertmanager/config.yml"
    ports:
      - "9093:9093"
    networks:
      - observanet

  grafana:
    image: grafana/grafana:latest
    container_name: observa-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/provisioning/dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - "3000:3000"
    networks:
      - observanet
    depends_on:
      - prometheus

networks:
  observanet:
    driver: bridge