{
 "title": "Observa - Saúde do Serviço",
 "tags": [
  "observability",
  "demo"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Erro (%) - 30s",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(http_requests_total{status=~\"5..\"}[30s])) / sum(rate(http_requests_total[30s]))",
     "legendFormat": "error%"
    }
   ]
  },
  {
   "title": "Erro %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum by (route) (rate(http_requests_total{status=~\"5..\"}[1m])) / sum by (route) (rate(http_requests_total[1m]))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Latência p95 (s) - 1m",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Latência p95 (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, route) (rate(http_request_duration_seconds_bucket[1m])))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Throughput (req/s) - 30s",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[30s]))",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "Requests por segundo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "sum by (route) (rate(http_requests_total[30s]))",
     "legendFormat": "{{route}}"
    }
   ]
  }
 ]
}